CREATE TABLE [MLOutput].[StudentFinalGradeEstimate] (
StudentID int not null
,TermID int not null
,SubjectID varchar(10) not null
,CatalogID varchar(10) not null
,ClassID int not null
,SectionID varchar(5) not null
,FinalGradeEstimate varchar(1) not null
,ProbabilityFinalGradeA float not null
,ProbabilityFinalGradeB float not null
,ProbabilityFinalGradeC float not null
,ProbabilityFinalGradeD float not null
,ProbabilityFinalGradeF float not null
,AzureMLTimestamp datetime default GETDATE());