CREATE TABLE [MLOutput].[StudentDropClass] (
StudentID int not null
,TermID int not null
,SubjectID varchar(10) not null
,CatalogID varchar(10) not null
,ClassID int not null
,SectionID varchar(5) not null
,EnrollDate int not null
,DropoutFlag int not null
,DropoutProbability float not null
,RiskCategory varchar(16) not null
,AzureMLTimestamp datetime default GETDATE());
